import React from 'react';
import { X, BookOpen, Check, Calculator, ShieldCheck } from 'lucide-react';

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  darkMode: boolean;
}

export const FinancialGlossaryModal: React.FC<ModalProps> = ({
  isOpen,
  onClose,
  darkMode,
}) => {
  if (!isOpen) return null;

  const bgModal = darkMode ? 'bg-slate-900 text-slate-100 border-slate-800' : 'bg-white text-slate-900 border-slate-200';

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-xs animate-in fade-in duration-200">
      <div className={`w-full max-w-3xl max-h-[85vh] rounded-2xl border ${bgModal} shadow-2xl flex flex-col overflow-hidden`}>
        {/* Header */}
        <div className="p-4 sm:p-5 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <BookOpen className="h-5 w-5 text-emerald-500" />
            <h2 className="text-lg font-bold tracking-tight">DCF Valuation Guide & Formula Reference</h2>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-5 overflow-y-auto space-y-6 text-xs sm:text-sm leading-relaxed">
          {/* Section 1: FCFF */}
          <div className="space-y-2">
            <h3 className="font-bold text-emerald-600 dark:text-emerald-400 flex items-center gap-1.5 text-sm sm:text-base">
              <Calculator className="h-4 w-4" />
              1. Free Cash Flow to Firm (FCFF)
            </h3>
            <p className="text-slate-600 dark:text-slate-300">
              Unlevered Free Cash Flow represents the cash generated by core operations available to all capital providers (both debt and equity holders) after paying operating expenses, taxes, and working capital / capex reinvestment.
            </p>
            <div className="p-3 rounded-xl bg-slate-100 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 font-mono text-xs">
              FCFF = EBIT × (1 − Tax Rate) + Depreciation & Amortization − Capital Expenditures − Δ Working Capital
            </div>
          </div>

          {/* Section 2: WACC & Discounting */}
          <div className="space-y-2">
            <h3 className="font-bold text-emerald-600 dark:text-emerald-400 flex items-center gap-1.5 text-sm sm:text-base">
              <Calculator className="h-4 w-4" />
              2. Discounting & WACC
            </h3>
            <p className="text-slate-600 dark:text-slate-300">
              The Weighted Average Cost of Capital (WACC) reflects the blended cost of equity and debt financing. Cash flows in year <em>t</em> are discounted using the discount factor <code>1 / (1 + WACC)<sup>t</sup></code>.
            </p>
            <div className="p-3 rounded-xl bg-slate-100 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 font-mono text-xs">
              PV(FCFF<sub>t</sub>) = FCFF<sub>t</sub> ÷ (1 + WACC)<sup>t</sup>
            </div>
          </div>

          {/* Section 3: Terminal Value Methods */}
          <div className="space-y-2">
            <h3 className="font-bold text-emerald-600 dark:text-emerald-400 flex items-center gap-1.5 text-sm sm:text-base">
              <Calculator className="h-4 w-4" />
              3. Terminal Value (TV) Methods
            </h3>
            <p className="text-slate-600 dark:text-slate-300">
              Terminal value estimates the value of all cash flows beyond the explicit forecast period.
            </p>
            <ul className="list-disc pl-5 space-y-1 text-slate-600 dark:text-slate-300">
              <li>
                <strong>Perpetual Growth Method (Gordon Growth):</strong> Assumes cash flows grow at a constant rate <em>g</em> into perpetuity.
                <div className="p-2 my-1 rounded-lg bg-slate-100 dark:bg-slate-950 font-mono text-xs">
                  TV = FCFF<sub>n</sub> × (1 + g) ÷ (WACC − g)
                </div>
              </li>
              <li>
                <strong>Exit Multiple Method:</strong> Applies an EBITDA transaction multiple to the final year forecast EBITDA.
                <div className="p-2 my-1 rounded-lg bg-slate-100 dark:bg-slate-950 font-mono text-xs">
                  TV = EBITDA<sub>n</sub> × Exit Multiple
                </div>
              </li>
            </ul>
          </div>

          {/* Section 4: EV & Equity Value Bridge */}
          <div className="space-y-2">
            <h3 className="font-bold text-emerald-600 dark:text-emerald-400 flex items-center gap-1.5 text-sm sm:text-base">
              <Calculator className="h-4 w-4" />
              4. Enterprise Value to Equity Value Bridge
            </h3>
            <div className="p-3 rounded-xl bg-slate-100 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 font-mono text-xs space-y-1">
              <div>Enterprise Value = PV(Forecast Cash Flows) + PV(Terminal Value)</div>
              <div>Equity Value = Enterprise Value + Cash + Non-Operating Investments − Debt − Minority Interest − Preferred Equity</div>
              <div>Intrinsic Value Per Share = Equity Value ÷ Diluted Shares Outstanding</div>
            </div>
          </div>

          {/* Section 5: Margin of Safety */}
          <div className="space-y-2">
            <h3 className="font-bold text-emerald-600 dark:text-emerald-400 flex items-center gap-1.5 text-sm sm:text-base">
              <ShieldCheck className="h-4 w-4" />
              5. Margin of Safety & Upside
            </h3>
            <p className="text-slate-600 dark:text-slate-300">
              Popularized by Benjamin Graham and Warren Buffett, the Margin of Safety represents the discount between intrinsic valuation and the current market market price. A higher margin of safety reduces investment downside risk.
            </p>
            <div className="p-3 rounded-xl bg-slate-100 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 font-mono text-xs">
              Margin of Safety (%) = (Intrinsic Value − Market Price) ÷ Intrinsic Value × 100
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-200 dark:border-slate-800 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-semibold text-xs transition-colors"
          >
            Close Guide
          </button>
        </div>
      </div>
    </div>
  );
};
